services:
  app:
    build:
      context: ../  
      dockerfile: config/Dockerfile
    container_name: echo_flow
    working_dir: /app
    networks:
      - deploy_net
    env_file:
      - ../app.env
    expose:
      - "5000"

networks:
  deploy_net:
    external: true

volumes:
  ollama_data:
